apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cloudflared-egress
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
    - Egress
  egress:
    # Cloudflare Tunnel 制御通信
    - ports:
        - protocol: TCP
          port: 443
        - protocol: UDP
          port: 443
        - protocol: TCP
          port: 7844
        - protocol: UDP
          port: 7844
    # DNS解決
    - ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # namespace内の他のServiceへのアクセス
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
