apiVersion: v1
kind: Secret
metadata:
    name: hermes-yukulab-secrets
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:7rZJDiwel1rehl91/17MCJT6vIbRdGzXTZ/tSg==,iv:QjKC6ZGXbUnBow7Y5PNCGCyl7KsNle4sYfMeMiKGi84=,tag:8dXA5+UaGpeRJ5BadKZUhw==,type:str] #ENC[AES256_GCM,data:7rjMgEtnojT+NQqxwEbqTsq7YQY4mj4IzgAkIXeUxy4sPavsKFE=,iv:cViKJUtRaXjta5LuV/YkLZYxbCIhwgrSUrN+yf2Ee/k=,tag:/OyO8FJiry6ZeUAyKcF1/Q==,type:comment]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:tQ/T+rwgU/Quhez3xhZEij65+tWg3PPQK56BjnENnEbxZB8IOBaqjFR58N2BiMAM4UMfEjNjuc3Ar2PuAZf2UOAZHU02zLXp,iv:h7orUfdVkHbQOOED4DW97Q5Rb2faoJa/AgsqOuj32sU=,tag:SMi2sZFzpL7NkUJ4D5P4QA==,type:str] #ENC[AES256_GCM,data:vi/Vat28on5IWgGqt5fTHiw=,iv:RA7UC9aWcdru2iPs2v9pWmHFrmug5t4xVul44CznlIg=,tag:uDTFKCeM0TPeoKnYCEosmQ==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:D+rIoF/VIGqguuPeh5xkEMRB7zWW50A8JxLLMmsuMa/6YaUUpBdnqSueE6WDBM14q8MSyuslAdd1rnE3S1hOhZu2LTfLWdMc0noN4X1157v3b9vxaNjxk9Ai57ps,iv:rrj4eAfTXLqyGZWHFa44Ma6JZxqW4DQoHzh8/E3/OkY=,tag:dmUe2P1g3YpmEE8DIScRog==,type:str] #ENC[AES256_GCM,data:trMVF8QMIcxs1XEz1AW3yjtGRv0=,iv:0e9ByFw9FgaKjYpyL1rDHxmJfKFx6RV24sTbft4JOc8=,tag:AT81ZRmXaEvXlN3cRrAICg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEemNkTmNUUzYwSjVZcVhZ
            YXFQdW1CSG1NS21rREFKaDVVMVNadmdSTjBFCnJmclNRS0VPZk5CdnN1RmMrUWJN
            RmR2aElrQ01oMXljU1NWOWlyNUtROTAKLS0tIDNDNFBlVmJZQ0hVL2QrdHFXL2t6
            Z1lPOElOUElNWVZvTTZDRkkrU1dqOFUK7+4RJkUSy0CksTkoaFb0znp/dMIsXWyq
            xME8qCc7XJ7s4LI7x4XQCp3LmMhyN81VBIZA7UQu0+dOckPj7S00QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1df3n8tr6qd4lnusczvtl5vyhwahh95ym853p0nm4addp8wpza46qdt7fdf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T08:39:23Z"
    mac: ENC[AES256_GCM,data:FeYFsyGj6a4bn61PdcO6JS1U5NEyBOyeG7Qg3y26nPMqnFxQ1apPDJqGUq9zbLB+yuL6TvGKNJHxEkDnN3F5UbdzO2DV5SGpRp+8DVFpz0YI1JS5TGRTH3JoSFWRMeqjMs6Cyl6WjkKFLy4t6/tN6pOK3PIODL1DxmyXo7x5t8o=,iv:2zjs7zO/aXTRaJXtPthPjCl4YAJLK0y7nsXiGKvXZEc=,tag:Bac5fQUcNsbR6od9y7SHXw==,type:str]
    version: 3.13.1
