apiVersion: v1
kind: Secret
metadata:
    name: hermes-yukulab-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7rjMgEtnojT+NQqxwEbqTsq7YQY4mj4IzgAkIXeUxy4sPavsKFE=,iv:cViKJUtRaXjta5LuV/YkLZYxbCIhwgrSUrN+yf2Ee/k=,tag:/OyO8FJiry6ZeUAyKcF1/Q==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:7rZJDiwel1rehl91/17MCJT6vIbRdGzXTZ/tSg==,iv:QjKC6ZGXbUnBow7Y5PNCGCyl7KsNle4sYfMeMiKGi84=,tag:8dXA5+UaGpeRJ5BadKZUhw==,type:str]
    #ENC[AES256_GCM,data:vi/Vat28on5IWgGqt5fTHiw=,iv:RA7UC9aWcdru2iPs2v9pWmHFrmug5t4xVul44CznlIg=,tag:uDTFKCeM0TPeoKnYCEosmQ==,type:comment]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:tQ/T+rwgU/Quhez3xhZEij65+tWg3PPQK56BjnENnEbxZB8IOBaqjFR58N2BiMAM4UMfEjNjuc3Ar2PuAZf2UOAZHU02zLXp,iv:h7orUfdVkHbQOOED4DW97Q5Rb2faoJa/AgsqOuj32sU=,tag:SMi2sZFzpL7NkUJ4D5P4QA==,type:str]
    #ENC[AES256_GCM,data:trMVF8QMIcxs1XEz1AW3yjtGRv0=,iv:0e9ByFw9FgaKjYpyL1rDHxmJfKFx6RV24sTbft4JOc8=,tag:AT81ZRmXaEvXlN3cRrAICg==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:jSMpORkLXivtAlD3KrXm3TnhasSGQVpPumHTYgDiqO+9jrm28e6fiiF6+eQ+Iyz/n7nVQ/KxGGgJXOaESRmvZk2TvKFSsEdM2UFVfvkECysTvscmCe+Mt/n0dC3F,iv:i3qPBUcGxnDgVbQSbRZmtQRmvQ4ojj6mkp168BR7Ipk=,tag:O+oXOP+4QVt87ivWj61Fjg==,type:str]
    #ENC[AES256_GCM,data:StdbeRf6VV5QjToTjImDXwD9L1vjlWY=,iv:jqybKX3b+OkTCXqVdN0iqiklNwHkfst/jzpzxu/UINk=,tag:8yL5Zi1j5O+tqAKOSkOzbg==,type:comment]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:PXBw/5oL4p+XrHPGGJa7ljh9R6g=,iv:EzbrsdqrdYrp0JoOClgBkuouZwQv2QvUxikVRf6jjiA=,tag:/Tltw63t68c+63Pxj8y7gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEemNkTmNUUzYwSjVZcVhZ
            YXFQdW1CSG1NS21rREFKaDVVMVNadmdSTjBFCnJmclNRS0VPZk5CdnN1RmMrUWJN
            RmR2aElrQ01oMXljU1NWOWlyNUtROTAKLS0tIDNDNFBlVmJZQ0hVL2QrdHFXL2t6
            Z1lPOElOUElNWVZvTTZDRkkrU1dqOFUK7+4RJkUSy0CksTkoaFb0znp/dMIsXWyq
            xME8qCc7XJ7s4LI7x4XQCp3LmMhyN81VBIZA7UQu0+dOckPj7S00QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1df3n8tr6qd4lnusczvtl5vyhwahh95ym853p0nm4addp8wpza46qdt7fdf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T03:44:23Z"
    mac: ENC[AES256_GCM,data:vo3rNF5FAHSgeuX6DSPY00NjlqwiFVx6U5qPs0QxNKqYy4g9BxcB68RCMmdXYlWGrFAcMKCtJJqkMmSekGHy42KK15TErtMuzBom5l1l2Nq1ZtM3AhOm0FLVSD2WV9JbG+yd90i7pVLaOFefxIBxJCFvsBM7PsqyYCts/yna05s=,iv:3H5unRDnkiwmEK6cj1amsndKNKHt5m0T4EoeOOREyXY=,tag:Gw/+0TL+AKPkJXLrXnMC8w==,type:str]
    version: 3.13.1
